
// This is a mock database using localStorage to simulate a backend.
// In a real application, this would be a secure, server-side database.
// All data is stored as JSON strings.

import type { User, Transaction, Log, StoredFile } from '../types';

const DB_PREFIX = 'secure_vault_';
const USERS_KEY = `${DB_PREFIX}users`;
const TRANSACTIONS_KEY = `${DB_PREFIX}transactions`;
const LOGS_KEY = `${DB_PREFIX}logs`;
const FILES_KEY = `${DB_PREFIX}files`;

const get = <T,>(key: string): T[] => {
  try {
    const data = localStorage.getItem(key);
    return data ? JSON.parse(data) : [];
  } catch (e) {
    console.error(`Failed to read from localStorage key "${key}"`, e);
    return [];
  }
};

const set = <T,>(key: string, data: T[]): void => {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (e) {
    console.error(`Failed to write to localStorage key "${key}"`, e);
  }
};

// Initialize with a default user if none exist
const initializeDefaultUser = () => {
    const users = get<User>(USERS_KEY);
    if (users.length === 0) {
        // This is a mock hash. In a real app, this is generated by bcrypt.
        // The password is "Password123!"
        const defaultUser: User = {
            userId: 'user-1',
            username: 'admin',
            email: 'admin@example.com',
            passwordHash: '$2a$10$f/....aVeryLongAndSecureHash....', 
            createdAt: new Date().toISOString()
        };
        set<User>(USERS_KEY, [defaultUser]);
    }
};

// Call initialization
initializeDefaultUser();


export const db = {
  users: {
    getAll: () => get<User>(USERS_KEY),
    add: (user: User) => set<User>(USERS_KEY, [...get<User>(USERS_KEY), user]),
    update: (updatedUser: User) => {
        const users = get<User>(USERS_KEY);
        const newUsers = users.map(u => u.userId === updatedUser.userId ? updatedUser : u);
        set<User>(USERS_KEY, newUsers);
    },
    findByUsername: (username: string) => get<User>(USERS_KEY).find(u => u.username === username),
    findById: (userId: string) => get<User>(USERS_KEY).find(u => u.userId === userId),
  },
  transactions: {
    getAllByUserId: (userId: string) => get<Transaction>(TRANSACTIONS_KEY).filter(t => t.userId === userId),
    add: (transaction: Transaction) => set<Transaction>(TRANSACTIONS_KEY, [...get<Transaction>(TRANSACTIONS_KEY), transaction]),
  },
  logs: {
    getAllByUserId: (userId: string) => get<Log>(LOGS_KEY).filter(l => l.userId === userId),
    add: (log: Log) => set<Log>(LOGS_KEY, [...get<Log>(LOGS_KEY), log]),
  },
  files: {
    getAllByUserId: (userId: string) => get<StoredFile>(FILES_KEY).filter(f => f.userId === userId),
    add: (file: StoredFile) => set<StoredFile>(FILES_KEY, [...get<StoredFile>(FILES_KEY), file]),
  }
};
